name: 'cd-master'

on:
  pull_request:
    types: [closed]
    branches:
      - master
  push:
    branches:
      - master

env:
  TF_IN_AUTOMATION: true

jobs:
  terraform-apply:
    name: Apply
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    env:
      KEY_PREFIX_NAME: ${{ github.event.repository.name }}
      KEY_NAME: master

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-duration-seconds: 1800
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Adapt AWS Terraform Backend
        id: aws-backend-write
        run: |
          cd ./terraform
          sed -i -e "s/__KEY_PREFIX_NAME__/$KEY_PREFIX_NAME/g" ./provider.tf
          sed -i -e "s/__KEY_NAME__/$KEY_NAME/g" ./provider.tf
          sed -i -e "s/__KEY_NAME__/$KEY_NAME/g" ./terraform.tfvars          
          cat ./provider.tf
          cat ./terraform.tfvars 
          cd ..

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.1.9'

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform new Workspace
        run: terraform workspace select $workspace || terraform workspace new $workspace
        working-directory: terraform
        env:
          workspace: ${{ env.KEY_PREFIX_NAME }}-${{ env.KEY_NAME }}

      - name: Terraform Apply
        id: Apply
        #run: terraform apply -auto-approve -var 'tf_branch=master'
        run: terraform apply -destroy -auto-approve -var 'tf_branch=master'        
        working-directory: terraform
        env:
          TF_WORKSPACE: ${{ env.KEY_PREFIX_NAME }}-${{ env.KEY_NAME }}
