name: Destroy review application on Amazon Elastic Beanstalk

on:
  pull_request:
    types: [closed, unlabeled]

env:
  TF_IN_AUTOMATION: true

jobs:
  terraform-destroy:
    name: Destroy
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    env:
      KEY_PREFIX_NAME: ${{ github.event.repository.name }}
      KEY_NAME: ${{ github.event.number }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-duration-seconds: 900
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Adapt AWS Terraform Backend
        id: aws-backend-write
        run: |
          cd ./terraform
          sed -i -e "s/__KEY_PREFIX_NAME__/$KEY_PREFIX_NAME/g" ./provider.tf
          sed -i -e "s/__KEY_NAME__/$KEY_NAME/g" ./provider.tf
          cat ./provider.tf
          cd ..

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.1.9'

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Destroy
        id: Destroy
        if: github.event_name == 'pull_request'
        run: terraform apply -destroy -auto-approve -var 'tf_branch=${{ github.head_ref }}'
        working-directory: terraform
        env:
          TF_WORKSPACE: ${{ env.KEY_PREFIX_NAME }}-pr-${{ env.KEY_NAME }}
